# Generated by Django 3.1.3 on 2022-04-27 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0096_auto_20220427_1843'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='appoint',
        #    name='pat',
        #    field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MySite.patient'),
        #),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 18, 45, 35, 229902)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 18, 45, 35, 228902)),
        ),
    ]
