# Generated by Django 3.1.3 on 2022-04-27 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0104_auto_20220427_1921'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='appoint',
        #    name='pat',
        #),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 21, 23, 201008)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 21, 23, 200011)),
        ),
    ]
