# Generated by Django 3.1.3 on 2022-04-27 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0108_auto_20220427_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 23, 34, 529879)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='pat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 23, 34, 528853)),
        ),
    ]
