# Generated by Django 3.1.3 on 2022-04-27 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0112_auto_20220427_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=20)),
                ('appointdate', models.DateField()),
                ('appointtime', models.TimeField(default='00:00')),
                ('appointreg', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 34, 3, 356191))),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MySite.person')),
                ('name', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        #migrations.RemoveConstraint(
        #    model_name='doctor',
        #    name='unique appointment',
        #),
        #migrations.RemoveConstraint(
        #    model_name='doctor',
        #    name='unique_appdoc',
        #),
        #migrations.RemoveConstraint(
        #    model_name='doctor',
        #    name='unique_apppatient',
        #),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 34, 3, 355157)),
        ),
        migrations.AddField(
            model_name='appoint',
            name='doc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MySite.doctor'),
        ),
        migrations.AddField(
            model_name='appoint',
            name='pat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MySite.patient'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient', 'appointdate', 'appointtime'), name='unique appointment'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointdate', 'appointtime'), name='unique_appdoc'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('patient', 'appointdate', 'appointtime'), name='unique_apppatient'),
        ),
    ]
