# Generated by Django 3.1.3 on 2022-04-27 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0115_auto_20220427_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=20)),
                ('appointdate', models.DateField()),
                ('appointtime', models.TimeField(default='00:00')),
                ('appointreg', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 22, 6, 57, 796209))),
            ],
        ),
        # migrations.RemoveConstraint(
        #     model_name='doctor',
        #     name='unique appointment',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='doctor',
        #     name='unique_appdoc',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='doctor',
        #     name='unique_apppatient',
        # ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 22, 6, 57, 795212)),
        ),
        migrations.AddField(
            model_name='appoint',
            name='doc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MySite.doctor'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient', 'appointdate', 'appointtime'), name='unique appointment'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointdate', 'appointtime'), name='unique_appdoc'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('patient', 'appointdate', 'appointtime'), name='unique_apppatient'),
        ),
    ]
