# Generated by Django 3.1.3 on 2022-04-28 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0123_auto_20220427_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='userid',
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 13, 38, 42, 927830)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 13, 38, 42, 926832)),
        ),
    ]
