# Generated by Django 3.1.3 on 2022-04-28 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0124_auto_20220428_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='userid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySite.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='userid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySite.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 14, 0, 16, 111319)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 14, 0, 16, 110315)),
        ),
    ]
