# Generated by Django 3.1.3 on 2022-04-28 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0125_auto_20220428_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 14, 7, 14, 361004)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='MySite.person'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='MySite.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 14, 7, 14, 359974)),
        ),
    ]
