# Generated by Django 3.1.3 on 2022-04-28 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0128_auto_20220428_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='appoint',
            name='pat',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 14, 42, 31, 736620)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 14, 42, 31, 734658)),
        ),
    ]
