# Generated by Django 3.1.3 on 2022-04-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0129_auto_20220428_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='userid',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 19, 37, 38, 201110)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 19, 37, 38, 200111)),
        ),
    ]
