# Generated by Django 3.1.3 on 2022-04-28 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0130_auto_20220428_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 19, 47, 1, 685112)),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 19, 47, 1, 685112)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 19, 47, 1, 685112)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 19, 47, 1, 684119)),
        ),
        # migrations.AddConstraint(
        #     model_name='doctor',
        #     constraint=models.UniqueConstraint(fields=('login', 'password'), name='unique_doctor'),
        # ),
        # migrations.AddConstraint(
        #     model_name='patient',
        #     constraint=models.UniqueConstraint(fields=('login', 'password'), name='unique_patient'),
        # ),
    ]
