# Generated by Django 3.1.3 on 2022-04-28 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0131_auto_20220428_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='docprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 17, 45, 273100)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 17, 45, 272101)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 17, 45, 272101)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 17, 45, 272101)),
        ),
    ]
