# Generated by Django 3.1.3 on 2022-04-28 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0135_auto_20220428_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySite.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySite.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 29, 28, 357541)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 29, 28, 356542)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 29, 28, 356542)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 29, 28, 355544)),
        ),
    ]
