# Generated by Django 3.1.3 on 2022-04-28 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0136_auto_20220428_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='typedoctor',
            new_name='usertype',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profile',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 38, 46, 787608)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 38, 46, 779574)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 38, 46, 778578)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 21, 38, 46, 778578)),
        ),
    ]
