# Generated by Django 3.1.3 on 2022-05-01 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0137_auto_20220428_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='login',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='login',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 12, 26, 22, 592651)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 12, 26, 22, 592651)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 12, 26, 22, 591654)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 12, 26, 22, 591654)),
        ),
    ]
