# Generated by Django 3.1.3 on 2022-05-04 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0141_auto_20220501_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 20, 37, 20, 340333)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 20, 37, 20, 324711)),
        ),
    ]
