# Generated by Django 3.1.3 on 2022-05-08 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0142_auto_20220504_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 8, 15, 20, 53, 207398)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 15, 20, 53, 207398)),
        ),
    ]
