# Generated by Django 3.1.3 on 2022-04-27 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0109_auto_20220427_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='doc',
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 32, 29, 41837)),
        ),
        #migrations.AddConstraint(
        #    model_name='doctor',
        #    constraint=models.UniqueConstraint(fields=('doctor', 'patient', 'appointdate', 'appointtime'), name='unique appointment'),
        #),
        #migrations.AddConstraint(
        #    model_name='doctor',
        #    constraint=models.UniqueConstraint(fields=('doctor', 'appointdate', 'appointtime'), name='unique_appdoc'),
        #),
        #migrations.AddConstraint(
        #    model_name='doctor',
        #    constraint=models.UniqueConstraint(fields=('patient', 'appointdate', 'appointtime'), name='unique_apppatient'),
        #),
        migrations.DeleteModel(
            name='Appoint',
        ),
    ]
