# Generated by Django 3.1.3 on 2022-04-27 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0111_auto_20220427_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 19, 33, 45, 338305)),
        ),
    ]
