# Generated by Django 3.1.3 on 2022-04-28 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0132_auto_20220428_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 25, 57, 585281)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 25, 57, 584254)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 25, 57, 584254)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 25, 57, 584254)),
        ),
    ]
