# Generated by Django 3.1.3 on 2022-04-28 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0133_auto_20220428_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 36, 31, 113668)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySite.docprofile'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 36, 31, 113668)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 36, 31, 112669)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 20, 36, 31, 112669)),
        ),
    ]
