# Generated by Django 3.1.3 on 2022-05-01 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0138_auto_20220501_1226'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='doctor',
        #     name='unique_doctor',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='patient',
        #     name='unique_patient',
        # ),
        migrations.RemoveField(
            model_name='doctor',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registered',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 12, 30, 45, 794900)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 12, 30, 45, 792905)),
        ),
    ]
