# Generated by Django 3.1.3 on 2022-05-01 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0139_auto_20220501_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 15, 38, 6, 250292)),
        ),
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 15, 38, 6, 250292)),
        ),
    ]
