# Generated by Django 3.1.3 on 2022-05-10 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0143_auto_20220508_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 0, 11, 3, 802842)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 0, 11, 3, 787221)),
        ),
    ]
